version: "3.9"

services:
  db:
    image: mysql:8.0.27
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sword
      MYSQL_USER: dvn
      MYSQL_PASSWORD: secret

  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"

  web-server:
    restart: on-failure
    depends_on:
      - db
      - rabbitmq
    build: .
    ports:
      - "8081:8080"
    environment:
      DB_HOST: db:3306
      DB_USER: dvn
      DB_PASSWORD: secret
      DB_NAME: sword
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672
      AES_KEY: 36e6b12a3cae77805da5f95ccd378da9

volumes:
  db_data: {}

