version: "3.9"

services:
  db:
    image: mysql:8.0.27
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sword
      MYSQL_USER: dvn
      MYSQL_PASSWORD: secret

  web-server:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db:3306
      DB_USER: dvn
      DB_PASSWORD: secret
      DB_NAME: sword
volumes:
  db_data: {}

